# Generated by Django 3.2.5 on 2021-08-17 23:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Totals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_total', models.FloatField(default=0, max_length=50)),
                ('netflix', models.FloatField(default=0, max_length=50)),
                ('num_line', models.PositiveIntegerField(default=1, verbose_name='Number of lines')),
                ('total_bill', models.FloatField(default=0, max_length=50, null=True)),
                ('note', models.TextField(default='Please visit www.vangarmoh.com to upload screenshot of your payment confirmation page. username is: your phone number. Password is: the first two digits and last two digits of your phone number. Thank you.', max_length=400)),
                ('bill_date', models.DateField(default=datetime.datetime(2021, 8, 17, 18, 31, 57, 696287))),
            ],
        ),
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, default='Learn more', max_length=250, null=True)),
                ('announcement', models.TextField(max_length=400)),
                ('link', models.URLField(blank=True, null=True)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2021, 8, 17, 18, 31, 57, 695287))),
            ],
        ),
        migrations.CreateModel(
            name='UserGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_gender', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(null=True, upload_to='media/', verbose_name='Upload the screenshot of the payment you made (in T-Mobile app, zelle, or Cash App')),
                ('total_paid', models.FloatField(default=0, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, max_length=400, null=True, verbose_name='Remark or comment')),
                ('date_created', models.DateField(default=datetime.datetime(2021, 8, 17, 18, 31, 57, 695287), verbose_name='Upload date')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=400, verbose_name='Comment or suggestions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=256, null=True)),
                ('monthly', models.FloatField(default=0, max_length=50, null=True)),
                ('original_price', models.FloatField(default=0, max_length=50, null=True)),
                ('down_pay', models.FloatField(default=0, max_length=50, null=True)),
                ('duration', models.IntegerField(default=0, null=True)),
                ('date_created', models.DateField(default=datetime.date(2021, 7, 23))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BreakDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.FloatField(default=0, max_length=50, null=True)),
                ('one_charge', models.FloatField(default=0, max_length=50, null=True)),
                ('add_on', models.FloatField(default=0, max_length=50, null=True)),
                ('mid_cycle', models.FloatField(default=0, max_length=50, null=True)),
                ('admin_comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
